# Generated by Django 4.0.4 on 2022-05-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goshop', '0002_alter_product_price_alter_subproduct_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='category/', verbose_name='Upload Category data'),
        ),
    ]
