# Generated by Django 4.0.4 on 2022-05-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goshop', '0003_category_csv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='csv_file',
        ),
    ]
