# Generated by Django 4.0.4 on 2022-05-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goshop', '0007_remove_product_image_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goshop.product', verbose_name='Product Parent'),
        ),
    ]
