# Generated by Django 4.0.4 on 2022-05-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goshop', '0008_alter_media_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='images/', verbose_name='Featured Image'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
